services:
  backend:
    build: 
      context: ./draganddrop/backend
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    container_name: backend
    # entrypoint: ['bash', entrypoint.sh]
    networks:
      - draganddrop_network
  
  frontend:
    build: 
      context: ./draganddrop/frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    container_name: frontend
    networks:
      - draganddrop_network
    env_file:
      - .env
    # depends_on:
    #   - backend


networks:
  draganddrop_network:
    driver: bridge
    
    