services:
  # ... backend и frontend остаются без изменений ...
  backend:
    build:
      context: ./draganddrop/backend
      dockerfile: Dockerfile
    container_name: draganddrop_backend_app
    networks:
      - draganddrop_network
    restart: unless-stopped

  frontend:
    build:
      context: ./draganddrop/frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: draganddrop_frontend_app
    networks:
      - draganddrop_network
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: draganddrop_nginx_proxy
    ports:
      - "80:80"
      - "443:443" # <--- Добавляем порт 443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt # <--- Пробрасываем конфигурацию Certbot
      - ./certbot/www:/var/www/certbot   # <--- Пробрасываем директорию для challenge
    networks:
      - draganddrop_network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

networks:
  draganddrop_network:
    driver: bridge